Backport: feat(mcp): export the json-rpc schema for requests and response (#16626)
This is an automated backport of #16553 to the release-v6.0 branch. FYI
@aayush-kapoor
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/docs/07-reference/01-ai-sdk-core/index.mdx
CONFLICT (content): Merge conflict in content/docs/07-reference/01-ai-sdk-core/index.mdx
Auto-merging packages/mcp/src/index.ts
Auto-merging packages/mcp/src/tool/mcp-http-transport.ts
CONFLICT (content): Merge conflict in packages/mcp/src/tool/mcp-http-transport.ts
error: could not apply 3c30eb4c8e... feat(mcp): export the json-rpc schema for requests and response (#16553)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>